version: '3.6'

services:
  flxwebapi:
    image: fabreguesm/notion-webhook-sync:latest
    hostname: notion-webhook-sync  
    networks:
      - traefik          
    deploy:      
      placement:
        constraints: ["${NODE}"] 
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=5000"      
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}    
networks:
  traefik:
    external:
      name: traefik
